In [54]:
import os
import json
import pandas as pd
import numpy as np
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter

def find_lat_long(cities):
    geolocator = Nominatim(user_agent="city_geocoder", timeout=10)
    geocode = RateLimiter(geolocator.geocode, min_delay_seconds=1)

    # load original data frame
    rain_data = pd.read_csv("D:\\Projects\\rain-in-Australia\\data\\weatherAUS.csv")

    # update location name
    rain_data.replace('BadgerysCreek', 'Badgerys Creek', inplace = True)
    rain_data.replace('CoffsHarbour', 'Coffs Harbour', inplace = True)
    rain_data.replace('NorahHead', 'Norah Head', inplace = True)
    rain_data.replace('NorfolkIsland', 'Norfolk Island', inplace = True)
    rain_data.replace('SydneyAirport', 'Sydney Airport', inplace = True)
    rain_data.replace('WaggaWagga', 'Wagga Wagga', inplace = True)
    rain_data.replace('MountGinini', 'Mount Ginini', inplace = True)
    rain_data.replace('MelbourneAirport', 'Melbourne Airport', inplace = True)
    rain_data.replace('GoldCoast', 'Gold Coast', inplace = True)
    rain_data.replace('MountGambier', 'Mount Gambier', inplace = True)
    rain_data.replace('PearceRAAF', 'RAAF Base Pearce', inplace = True)
    rain_data.replace('PerthAirport', 'Perth Airport', inplace = True)
    rain_data.replace('SalmonGums', 'Salmon Gums', inplace = True)
    rain_data.replace('AliceSprings', 'Alice Springs', inplace = True)
    rain_data.replace('Richmond', 'Richmond RAAF', inplace = True)
    rain_data.replace('Albury', 'Albury Airport', inplace = True)
    rain_data.replace('Portland', 'Portland Airport', inplace = True)
    rain_data.replace('Walpole', 'North Walpole', inplace = True)

    # unique location data frame
    city_data = pd.DataFrame(rain_data['Location'].unique(), columns=['City']) 

    # testing - only 2 rows
    city_data_test = city_data.head(2)

    latitude = []
    longitude = []
    
    for city in city_data_test["City"]:
        location = geocode(f"{city}, Australia")
        if location:
            lat, lon = location.latitude, location.longitude
        else:
            lat, lon = None, None

        latitude.append(lat)
        longitude.append(lon)

    latitude_df = pd.DataFrame(latitude, columns=['Latitude']) 
    longitude_df = pd.DataFrame(longitude, columns=['Longitude'])

    city_data_completed_test = pd.concat([city_data_test, latitude_df], axis=1)
    city_data_completed_test = pd.concat([city_data_completed_test, longitude_df], axis=1)
    
    return city_data_completed_test

In [45]:
print(list(city_data_test))

['City']

In [46]:
print(city_data_test.columns)

Index(['City'], dtype='str')

In [69]:
city_data_test = city_data.head(2)

In [70]:
city_data_test

             City
0  Albury Airport
1  Badgerys Creek

In [67]:
city_data_test

In [66]:
df.to_string()

NameError: name 'df' is not defined

In [58]:
os.getcwd()

'D:\\Projects\\rain-in-Australia\\dslc_documentation\\functions'

In [62]:
city_data_test

In [71]:
base_filename = 'Values.txt'
with open(os.path.join("D:\\Projects\\rain-in-Australia\\data", base_filename),'w') as outfile:
    city_data_test.to_string(outfile)
#Neatly allocate all columns and rows to a .txt file

In [51]:
city_data_test.to_txt(city_data_test, index=False)

AttributeError: 'DataFrame' object has no attribute 'to_txt'

In [33]:
import pandas as pd
import numpy as np

# load original data frame
rain_data = pd.read_csv("D:\\Projects\\rain-in-Australia\\data\\weatherAUS.csv")

# update location name
rain_data.replace('BadgerysCreek', 'Badgerys Creek', inplace = True)
rain_data.replace('CoffsHarbour', 'Coffs Harbour', inplace = True)
rain_data.replace('NorahHead', 'Norah Head', inplace = True)
rain_data.replace('NorfolkIsland', 'Norfolk Island', inplace = True)
rain_data.replace('SydneyAirport', 'Sydney Airport', inplace = True)
rain_data.replace('WaggaWagga', 'Wagga Wagga', inplace = True)
rain_data.replace('MountGinini', 'Mount Ginini', inplace = True)
rain_data.replace('MelbourneAirport', 'Melbourne Airport', inplace = True)
rain_data.replace('GoldCoast', 'Gold Coast', inplace = True)
rain_data.replace('MountGambier', 'Mount Gambier', inplace = True)
rain_data.replace('PearceRAAF', 'RAAF Base Pearce', inplace = True)
rain_data.replace('PerthAirport', 'Perth Airport', inplace = True)
rain_data.replace('SalmonGums', 'Salmon Gums', inplace = True)
rain_data.replace('AliceSprings', 'Alice Springs', inplace = True)
rain_data.replace('Richmond', 'Richmond RAAF', inplace = True)
rain_data.replace('Albury', 'Albury Airport', inplace = True)
rain_data.replace('Portland', 'Portland Airport', inplace = True)
rain_data.replace('Walpole', 'North Walpole', inplace = True)

# unique location data frame
city_data = pd.DataFrame(rain_data['Location'].unique(), columns=['City'])

In [36]:
city_data_test = city_data.head(2)

In [47]:
find_lat_long(city_data_test)

RateLimiter caught an error, retrying (0/2 tries). Called with (*('Albury Airport, Australia',), **{}).
Traceback (most recent call last):
  File "C:\Users\ausri\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\geopy\geocoders\base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
  File "C:\Users\ausri\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\geopy\adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
  File "C:\Users\ausri\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\geopy\adapters.py", line 500, in _request
    raise AdapterHTTPError(
    ...<4 lines>...
    )
geopy.adapters.AdapterHTTPError: Non-successful status code 429

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ausri\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\geopy\extra\rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
    ^^^^^^^
  File "C:\Users\ausri\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\geopy\extra\rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
  File "C:\Users\ausri\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\geopy\geocoders\nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ausri\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\geopy\geocoders\base.py", line 388, in _call_geocoder
    res = self._adapter_error_handler(error)
  File "C:\Users\ausri\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\geopy\geocoders\base.py", line 407, in _adapter_error_handler
    raise exc_cls(
        str(error), retry_after=get_retry_after(error.headers)
    ) from error
geopy.exc.GeocoderRateLimited: Non-successful status code 429
RateLimiter caught an error, retrying (1/2 tries). Called with (*('Albury Airport, Australia',), **{}).
Traceback (most recent call last):
  File "C:\Users\ausri\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\geopy\geocoders\base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
  File "C:\Users\ausri\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\geopy\adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
  File "C:\Users\ausri\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\geopy\adapters.py", line 500, in _request
    raise AdapterHTTPError(
    ...<4 lines>...
    )
geopy.adapters.AdapterHTTPError: Non-successful status code 429

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ausri\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\geopy\extra\rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
    ^^^^^^^
  File "C:\Users\ausri\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\geopy\extra\rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
  File "C:\Users\ausri\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\geopy\geocoders\nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ausri\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\geopy\geocoders\base.py", line 388, in _call_geocoder
    res = self._adapter_error_handler(error)
  File "C:\Users\ausri\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\geopy\geocoders\base.py", line 407, in _adapter_error_handler
    raise exc_cls(
        str(error), retry_after=get_retry_after(error.headers)
    ) from error
geopy.exc.GeocoderRateLimited: Non-successful status code 429
RateLimiter swallowed an error after 2 retries. Called with (*('Albury Airport, Australia',), **{}).
Traceback (most recent call last):
  File "C:\Users\ausri\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\geopy\geocoders\base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
  File "C:\Users\ausri\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\geopy\adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
  File "C:\Users\ausri\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\geopy\adapters.py", line 500, in _request
    raise AdapterHTTPError(
    ...<4 lines>...
    )
geopy.adapters.AdapterHTTPError: Non-successful status code 429

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ausri\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\geopy\extra\rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
    ^^^^^^^
  File "C:\Users\ausri\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\geopy\extra\rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
  File "C:\Users\ausri\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\geopy\geocoders\nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ausri\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\geopy\geocoders\base.py", line 388, in _call_geocoder
    res = self._adapter_error_handler(error)
  File "C:\Users\ausri\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\geopy\geocoders\base.py", line 407, in _adapter_error_handler
    raise exc_cls(
        str(error), retry_after=get_retry_after(error.headers)
    ) from error
geopy.exc.GeocoderRateLimited: Non-successful status code 429
RateLimiter caught an error, retrying (0/2 tries). Called with (*('Badgerys Creek, Australia',), **{}).
Traceback (most recent call last):
  File "C:\Users\ausri\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\geopy\geocoders\base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
  File "C:\Users\ausri\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\geopy\adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
  File "C:\Users\ausri\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\geopy\adapters.py", line 500, in _request
    raise AdapterHTTPError(
    ...<4 lines>...
    )
geopy.adapters.AdapterHTTPError: Non-successful status code 429

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ausri\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\geopy\extra\rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
    ^^^^^^^
  File "C:\Users\ausri\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\geopy\extra\rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
  File "C:\Users\ausri\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\geopy\geocoders\nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ausri\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\geopy\geocoders\base.py", line 388, in _call_geocoder
    res = self._adapter_error_handler(error)
  File "C:\Users\ausri\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\geopy\geocoders\base.py", line 407, in _adapter_error_handler
    raise exc_cls(
        str(error), retry_after=get_retry_after(error.headers)
    ) from error
geopy.exc.GeocoderRateLimited: Non-successful status code 429
RateLimiter caught an error, retrying (1/2 tries). Called with (*('Badgerys Creek, Australia',), **{}).
Traceback (most recent call last):
  File "C:\Users\ausri\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\geopy\geocoders\base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
  File "C:\Users\ausri\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\geopy\adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
  File "C:\Users\ausri\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\geopy\adapters.py", line 500, in _request
    raise AdapterHTTPError(
    ...<4 lines>...
    )
geopy.adapters.AdapterHTTPError: Non-successful status code 429

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ausri\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\geopy\extra\rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
    ^^^^^^^
  File "C:\Users\ausri\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\geopy\extra\rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
  File "C:\Users\ausri\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\geopy\geocoders\nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ausri\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\geopy\geocoders\base.py", line 388, in _call_geocoder
    res = self._adapter_error_handler(error)
  File "C:\Users\ausri\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\geopy\geocoders\base.py", line 407, in _adapter_error_handler
    raise exc_cls(
        str(error), retry_after=get_retry_after(error.headers)
    ) from error
geopy.exc.GeocoderRateLimited: Non-successful status code 429
RateLimiter swallowed an error after 2 retries. Called with (*('Badgerys Creek, Australia',), **{}).
Traceback (most recent call last):
  File "C:\Users\ausri\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\geopy\geocoders\base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
  File "C:\Users\ausri\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\geopy\adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
  File "C:\Users\ausri\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\geopy\adapters.py", line 500, in _request
    raise AdapterHTTPError(
    ...<4 lines>...
    )
geopy.adapters.AdapterHTTPError: Non-successful status code 429

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ausri\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\geopy\extra\rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
    ^^^^^^^
  File "C:\Users\ausri\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\geopy\extra\rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
  File "C:\Users\ausri\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\geopy\geocoders\nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ausri\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\geopy\geocoders\base.py", line 388, in _call_geocoder
    res = self._adapter_error_handler(error)
  File "C:\Users\ausri\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\geopy\geocoders\base.py", line 407, in _adapter_error_handler
    raise exc_cls(
        str(error), retry_after=get_retry_after(error.headers)
    ) from error
geopy.exc.GeocoderRateLimited: Non-successful status code 429

             City Latitude Longitude
0  Albury Airport     None      None
1  Badgerys Creek     None      None