In [13]:
import pandas as pd
import numpy as np

# load original data frame
rain_data = pd.read_csv("D:\\Projects\\rain-in-Australia\\data\\weatherAUS.csv")

# update location name
rain_data.replace('BadgerysCreek', 'Badgerys Creek', inplace = True)
rain_data.replace('CoffsHarbour', 'Coffs Harbour', inplace = True)
rain_data.replace('NorahHead', 'Norah Head', inplace = True)
rain_data.replace('NorfolkIsland', 'Norfolk Island', inplace = True)
rain_data.replace('SydneyAirport', 'Sydney Airport', inplace = True)
rain_data.replace('WaggaWagga', 'Wagga Wagga', inplace = True)
rain_data.replace('MountGinini', 'Mount Ginini', inplace = True)
rain_data.replace('MelbourneAirport', 'Melbourne Airport', inplace = True)
rain_data.replace('GoldCoast', 'Gold Coast', inplace = True)
rain_data.replace('MountGambier', 'Mount Gambier', inplace = True)
rain_data.replace('PearceRAAF', 'RAAF Base Pearce', inplace = True)
rain_data.replace('PerthAirport', 'Perth Airport', inplace = True)
rain_data.replace('SalmonGums', 'Salmon Gums', inplace = True)
rain_data.replace('AliceSprings', 'Alice Springs', inplace = True)
rain_data.replace('Richmond', 'Richmond RAAF', inplace = True)
rain_data.replace('Albury', 'Albury Airport', inplace = True)
rain_data.replace('Portland', 'Portland Airport', inplace = True)
rain_data.replace('Walpole', 'North Walpole', inplace = True)

# unique location data frame
city_data = pd.DataFrame(rain_data['Location'].unique(), columns=['City'])

In [7]:
cities

<StringArray>
[   'Albury Airport',    'Badgerys Creek',             'Cobar',
     'Coffs Harbour',             'Moree',         'Newcastle',
        'Norah Head',    'Norfolk Island',           'Penrith',
     'Richmond RAAF',            'Sydney',    'Sydney Airport',
       'Wagga Wagga',       'Williamtown',        'Wollongong',
          'Canberra',       'Tuggeranong',      'Mount Ginini',
          'Ballarat',           'Bendigo',              'Sale',
 'Melbourne Airport',         'Melbourne',           'Mildura',
              'Nhil',  'Portland Airport',          'Watsonia',
          'Dartmoor',          'Brisbane',            'Cairns',
        'Gold Coast',        'Townsville',          'Adelaide',
     'Mount Gambier',         'Nuriootpa',           'Woomera',
            'Albany',       'Witchcliffe',  'RAAF Base Pearce',
     'Perth Airport',             'Perth',       'Salmon Gums',
     'North Walpole',            'Hobart',        'Launceston',
     'Alice Springs',            'Darwin',         'Katherine',
             'Uluru']
Length: 49, dtype: str

In [15]:
city_data_test = city_data.head(2)

In [16]:
city_data_test

             City  Latitude  Longitude
0  Albury Airport       NaN        NaN
1  Badgerys Creek       NaN        NaN

In [14]:
city_data

                 City  Latitude  Longitude
0      Albury Airport       NaN        NaN
1      Badgerys Creek       NaN        NaN
2               Cobar       NaN        NaN
3       Coffs Harbour       NaN        NaN
4               Moree       NaN        NaN
5           Newcastle       NaN        NaN
6          Norah Head       NaN        NaN
7      Norfolk Island       NaN        NaN
8             Penrith       NaN        NaN
9       Richmond RAAF       NaN        NaN
10             Sydney       NaN        NaN
11     Sydney Airport       NaN        NaN
12        Wagga Wagga       NaN        NaN
13        Williamtown       NaN        NaN
14         Wollongong       NaN        NaN
15           Canberra       NaN        NaN
16        Tuggeranong       NaN        NaN
17       Mount Ginini       NaN        NaN
18           Ballarat       NaN        NaN
19            Bendigo       NaN        NaN
20               Sale       NaN        NaN
21  Melbourne Airport       NaN        NaN
22          Melbourne       NaN        NaN
23            Mildura       NaN        NaN
24               Nhil       NaN        NaN
25   Portland Airport       NaN        NaN
26           Watsonia       NaN        NaN
27           Dartmoor       NaN        NaN
28           Brisbane       NaN        NaN
29             Cairns       NaN        NaN
30         Gold Coast       NaN        NaN
31         Townsville       NaN        NaN
32           Adelaide       NaN        NaN
33      Mount Gambier       NaN        NaN
34          Nuriootpa       NaN        NaN
35            Woomera       NaN        NaN
36             Albany       NaN        NaN
37        Witchcliffe       NaN        NaN
38   RAAF Base Pearce       NaN        NaN
39      Perth Airport       NaN        NaN
40              Perth       NaN        NaN
41        Salmon Gums       NaN        NaN
42      North Walpole       NaN        NaN
43             Hobart       NaN        NaN
44         Launceston       NaN        NaN
45      Alice Springs       NaN        NaN
46             Darwin       NaN        NaN
47          Katherine       NaN        NaN
48              Uluru       NaN        NaN